"""rename name to full_name

Revision ID: 113427609c1e
Revises: 00f18b109b41
Create Date: 2025-04-07 06:41:52.125523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '113427609c1e'
down_revision: Union[str, None] = '00f18b109b41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=False))
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
